name: Build Aseprite for macOS

on:
  push:
    branches:
      - main  # 触发条件：当 main 分支有新的提交时触发
  workflow_dispatch:  # 手动触发：可以通过 GitHub Actions 页面手动运行

jobs:
  build:
    runs-on: macos-latest  # 执行环境：使用最新的 macOS
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # 检出仓库到工作目录
    
    - name: Update submodules
      run: git submodule update --init --recursive  # 更新子模块到最新版本
    
    - name: Install dependencies
      run: |
        brew update  # 更新 Homebrew
        brew install cmake ninja
        brew install skia
        
    - name: Configure and build Aseprite
      run: |
        mkdir build
        cd build
        cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=/usr/local/opt/skia \
          -DSKIA_OUT=/usr/local/opt/skia \
          ..
        cmake --build . --target aseprite --config Release
        
    - name: Package Aseprite for macOS
      run: |
        mkdir -p packaged
        cp bin/aseprite packaged/
        # 将其他必要文件（如资源、依赖库等）复制到 packaged 目录
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: aseprite-macos
        path: packaged
