name: Build aseprite for macOS
 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    runs-on: macOS-latest
 
    steps:
    - uses: actions/checkout@v2
 
    - name: Setup Dependencies
      run: |
        brew install cmake ninja pkg-config yasm
        brew install --c++ aom --build-from-source
    - name: Configure Build
      run: |
        ./configure --prefix=$(pwd)/_install --cc=clang --cxx=clang++ --osx-version-min=10.13
    - name: Build Aseprite
      run: |
        ninja -v
    - name: Install Aseprite
      run: |
        sudo ninja install
    - name: Notarize Aseprite
      if: github.repository == 'aseprite/aseprite'
      env:
        APP_BUNDLE_ID: com.aseprite.aseprite
        NOTARIZATION_USERNAME: ${{ secrets.NOTARIZATION_USERNAME }}
        NOTARIZATION_PASSWORD: ${{ secrets.NOTARIZATION_PASSWORD }}
      run: |
        ./notarize_macos.sh _install/bin/aseprite "$APP_BUNDLE_ID"
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      if: github.repository == 'aseprite/aseprite'
      with:
        name: aseprite-macOS
        path: _install
